test: fix distro bootstrap conveyorPacker tests, from sylabs 2984
vzokay/apptainer pull request #399
Opened 2024-11-12 10:52 UTC by vzokay

This pulls in sylabs PR
* sylabs/singularity# 2984

The original PR description was:
> Ensure there are yum/dnf tests that work for:
> 
>  * AMD64 and ARM64 architectures (previously amd64 only).
>  * EL9 and Fedora RPM db_backend / db_path (previously broken on most EL versions.
> 
> Ensure there are zypper tests that work for:
> 
>  * AMD64 and ARM64 architectures (previously only amd64, and not gated properly).
> 
> Closes sylabs/singularity# 2971

2024-11-12 11:13 UTC, vzokay commented
@DrDaveD 
All the tests are successful, but I'm not entirely sure how to go about `internal/pkg/build/sources/conveyorPacker_yum_test.go`. In the original PR, `yumDef` const is removed and all the example files have the same name, whereas we have both `dnfDef` and `yumDef` in `almalinux-amd64` that are different from other examples called `Apptainer`.

2024-11-12 23:00 UTC, DrDaveD approved these changes
Yes, we recently added a Dnf alias for Yum, so in some cases we test both. 

It looks to me like you did the right things.

2024-11-12 23:32 UTC, DrDaveD requested changes

2024-11-12 23:32 UTC, DrDaveD commented on internal/pkg/build/sources/conveyorPacker_yum_test.go
>  	if dnfErr != nil && yumErr != nil {
I take it back, now that I have looked more closely.  There is still work to be done.

First of all, the check a little later down in this function where it sets `def := dnfDef` is useless because there's always a `yum` command.  You can delete the `yumDef` and `dnfDef` constants and that section of code that sets the `def` variable.  Just use `yumDef` instead of `def`.

Secondly, there's a problem that in the almalinux-amd64 directory there's no `Apptainer` file because the code on the new line 53 is expecting it.  In fact it bothers me that the test is passing.  Aha, the test is [skipped](https://github.com/vzokay/apptainer/actions/runs/11795773866/job/32856218309?pr=399#step:7:713).  I presume that it is not considered a "short" unit test.  Now it bothers me that we have only been running the short unit tests and not all of them.  I wonder if there are a significant number of them failing.  I will check, but that's out of scope of this PR.

Anyway I think the solution is to rename the `almalinux-amd64/YumDef` file to `almalinux-amd64/Apptainer` and leave the DnfDef file as-is.  That will require also changing the references to it in the e2e test.

2024-11-19 19:13 UTC, DrDaveD approved these changes
The new test still gets normally skipped because the unit tests run on Ubuntu, but I tried running it on EL8 and, after changing "sqlite" to "bdb" (because it was EL8 and not EL9), the test passed.

2024-11-21 18:50 UTC, closed without merging